apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-hodr-ingress
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: hodr
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: {{ .Values.hodr.service.port }}
    - from:
        - podSelector:
            matchLabels:
              app: bran
      ports:
        - port: {{ .Values.hodr.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-hodr-to-bran
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: bran
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: {{ .Values.bran.service.port }}
    - from:
        - podSelector:
            matchLabels:
              app: bran
      ports:
        - port: {{ .Values.bran.service.port }}
