apiVersion: v1
kind: Service
metadata:
  name: hodr
  namespace: fampay
  labels:
    app: hodr
spec:
  type: ClusterIP
  selector:
    app: hodr
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
