apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hodr
  namespace: {{ .Values.global.namespace }}
  labels:
    app: hodr
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hodr
  template:
    metadata:
      labels:
        app: hodr
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.port }}"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      containers:
        - name: hodr
          image: "{{ .Values.global.imageRegistry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: HOST_ADDR
              value: "0.0.0.0:{{ .Values.service.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 5
